name: Build & publish Haroohie images
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./chokuretsu-devkitarm/Dockerfile
            image: ghcr.io/haroohie-club/chokuretsu-devkitarm
            title: Chokuretsu CI
            description: "CI container for building the translated Suzumiya Haruhi no Chokuretsu patch"
          - dockerfile: ./heiretsu-devkitppc/Dockerfile
            image: ghcr.io/haroohie-club/heiretsu-devkitppc
            title: Heiretsu CI
            description: CI container for building the translated Suzumiya Haruhi no Heiretsu patch
          - dockerfile: ./sl-flatpack/Dockerfile
            image: ghcr.io/haroohie-club/sl-flatpak
            title: Serial Loops Flatpak Builder
            description: CI container for building flatpak releases of Serial Loops
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ matrix.image }}
          labels: |
            org.opencontainers.image.authors=Haroohie Translation Club
            org.opencontainers.image.vendor=Haroohie Translation Club
            org.opencontainers.image.title=${{ matrix.title }}
            org.opencontainers.image.description=${{ matrix.description }}

      - name: Build and push Docker images
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}